name: Run JIRA API Tests

on:
  schedule:
    - cron: '0 0 * * 0' # Ejecutar a medianoche todos los domingos
  workflow_dispatch: # Permite ejecutar el workflow manualmente desde la interfaz de GitHub

jobs:
  jira-api-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Newman and html reporter
      run: npm install -g newman newman-reporter-html

    - name: Verify if PASSWORD secret is available
      run: |
        if [ -z "${{ secrets.PASSWORD }}" ]; then
          echo "PASSWORD secret is not set."
        else
          echo "PASSWORD secret is set."
        fi

    - name: Run Postman collection with detailed HTML report
      continue-on-error: true
      run: |
        # Export PASSWORD variable for Newman
        export PASSWORD=${{ secrets.PASSWORD }}
        
        # Run Newman with the environment file and injected password
        newman run jiraapitest.postman_collection.json \
        --environment TEST.postman_environment.json \
        --reporters cli,html \
        --reporter-html-export newman/report.html \
        --env-var "PASSWORD=${PASSWORD}"

    - name: Upload Test Report
      uses: actions/upload-artifact@v4
      with:
        name: postman-test-report
        path: newman/report.html

    - name: Print Newman log (if needed)
      run: cat newman/report.html

